// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 21.09.2026, 22:00:07
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/Rinat/Downloads/vue-admin-2/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/Rinat/Downloads/vue-admin-2/app/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/Rinat/Downloads/vue-admin-2/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/Rinat/Downloads/vue-admin-2/app/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/Rinat/Downloads/vue-admin-2/app/plugins/**/*.{js,ts,mjs}","C:/Users/Rinat/Downloads/vue-admin-2/app/composables/**/*.{js,ts,mjs}","C:/Users/Rinat/Downloads/vue-admin-2/app/utils/**/*.{js,ts,mjs}","C:/Users/Rinat/Downloads/vue-admin-2/app/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/Rinat/Downloads/vue-admin-2/app/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/Rinat/Downloads/vue-admin-2/app/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Users/Rinat/Downloads/vue-admin-2/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;